### ISSUE TITLE
Ability to close open hook tabs

### ISSUE THREAD

**Issue by lukespragg** [RustOxide/Oxide-2-Patcher#11]
![6fad1c5e5ebe1e35897ac3d85766d023](https://cloud.githubusercontent.com/assets/671337/4914074/fdc0841a-64bc-11e4-9302-804e576ce739.png)

**Comment by HellUnit** [comment]
Added in commit c5e33492affb6a6eda1ce498b7762c2e923b2059. Forgot to add to commit message. My apologies.

**Comment by lukespragg** [comment]
No worries. Thanks for the PR! :)
