### ISSUE TITLE
Add version to program window title

### ISSUE THREAD

**Issue by lukespragg** [RustOxide/Oxide-2-Patcher#29]

**Comment by HellUnit** [comment]
Were you wanting the version from AssemblyInfo.cs? If so, I've got that written in and will PR it.

**Comment by lukespragg** [comment]
That was my thought. I'm trying to get Travis to add the build number, but somehow it keeps failing when live. :/

**Comment by HellUnit** [comment]
Right now I've basically got this in PatcherForm.cs:

```
private Version version = System.Reflection.Assembly.GetExecutingAssembly().GetName().Version;

public PatcherForm()
        {
            InitializeComponent();
            this.Text = String.Format(this.Text, version);
        }
```

And the PatcherForm.Text property has been changed to "Oxide Patcher - Version {0}".
So right now the Form title displays as "Oxide Patcher - Version 1.0.0.0"

**Comment by lukespragg** [comment]
That'd probably be fine, though we'll likely end up using x.x.x publicly.
