### ISSUE TITLE
Flag/Unflag buttons aren't updated for existing tabs when Flag All/Unflag All is used

### ISSUE THREAD

**Issue by lukespragg** [RustOxide/Oxide-2-Patcher#34]
@HellUnit

**Comment by HellUnit** [comment]
Working on this too. I know what needs to be done, difficult part is doing it. I'm attempting to modify the UpdateHook method to enable/disable the flag/unflag buttons in the related tab (if it exists), but I'm having trouble "finding" the buttons within the TabControls.
