### ISSUE TITLE
Build number replacement via .travis.yml not working

### ISSUE THREAD

**Issue by lukespragg** [RustOxide/Oxide-2-Patcher#41]
Just a note for me. The code below should be working, but it isn't somehow.

```
sed -ri "s/Version\((.*).0.0\)/Version(\"\1.${TRAVIS_BUILD_NUMBER}.0\")/g" $TRAVIS_BUILD_DIR/OxidePatcher/Properties/AssemblyInfo.cs
```

**Comment by HellUnit** [comment]
I've got this working. I set up my own travis-ci to test it out. After a lot of trial and error and then finding out that git bash has sed built-in... I think I got it. I replaced:
```
sed -ri "s/Version\((.*).0.0\)/Version(\"\1.${TRAVIS_BUILD_NUMBER}.0\")/g" $TRAVIS_BUILD_DIR/OxidePatcher/Properties/AssemblyInfo.cs
```
with:
```
cp $TRAVIS_BUILD_DIR/OxidePatcher/Properties/AssemblyInfo.cs $TRAVIS_BUILD_DIR/OxidePatcher/Properties/AssemblyInfo.cs.tmp
sed -r "s/(Version)\(\"(.*).0.0\"\)/Version\(\"1\.$TRAVIS_BUILD_NUMBER\.0\.0\"\)/" $TRAVIS_BUILD_DIR/OxidePatcher/Properties/AssemblyInfo.cs.tmp >$TRAVIS_BUILD_DIR/OxidePatcher/Properties/AssemblyInfo.cs
rm $TRAVIS_BUILD_DIR/OxidePatcher/Properties/AssemblyInfo.cs.tmp
```
and it seems to be working properly now.
This of course replaces the minor version number with the current travis-build number. In my case, the title bar displayed "Oxide Patcher - Version 1.21.0"

**Comment by lukespragg** [comment]
That isn't the quite what I am going for. ;)

The \1 in replacement portion of the command is the regex that it is grabbing from the (.*) in the first, which works fine. You can also do inline replacement using -i like I have above without all the witchcraft you are trying to do in your one. I think the only issue may be that I am not including the quotation marks around the initial version, but in testing they weren't needed for some reason.

**Comment by lukespragg** [comment]
Yup, my theory was right! Not sure why it was working without them in the testing.

**Comment by HellUnit** [comment]
Glad ya got it! :-D
