### ISSUE TITLE
DLLs somehow still being included in .zip archive via deploy.sh

### ISSUE THREAD

**Issue by lukespragg** [RustOxide/Oxide-2-Patcher#42]
Unsure how this is happening, but likely that it is from the Travis-CI instance not being as clean as it's supposed to be. https://travis-ci.org/RustOxide/Oxide-2-Patcher/builds/47477360#L1394

**Comment by HellUnit** [comment]
I think its because they are still copied to the output directory even 
though they're included in the executable now. I'll have a look at it.

Sent with AquaMail for Android
http://www.aqua-mail.com

**Comment by lukespragg** [comment]
I removed them from the deploy.sh script, so I don't see how they are
unless Travis-CI isn't making a clean instance and the jobs are somehow
getting the same instance each time. :/

**Comment by HellUnit** [comment]
I gotcha. I thought about that earlier though. No need to have them copied 
into the build output directory anymore. I was going to open an issue for 
it myself.

Sent with AquaMail for Android
http://www.aqua-mail.com

**Comment by HellUnit** [comment]
Do you think it would help to do a 'rm -rf $HOME/temp/*' before zipping the directory? I don't see where the temp directory is ever cleaned out in the script.

**Comment by lukespragg** [comment]
Travis-CI instances are supposed to be fresh every job, so it is clean by
default.

**Comment by lukespragg** [comment]
Figured it out. The script was updating the old archive that was cloned from the snapshots branch, so the DLLs would never get removed. I switch to a different method which seems to work. :)

**Comment by HellUnit** [comment]
Huzzah!

Sent with AquaMail for Android
http://www.aqua-mail.com
