### ISSUE TITLE
Unflag for command-line patching

### ISSUE THREAD

**Issue by lukespragg** [RustOxide/Oxide-2-Patcher#49]

**Comment by HellUnit** [comment]
I've got it so you can pass an -unflag option to it and it will unflag all flagged hooks, save the opj file, and proceed with the patch, if that's what you were looking for.

**Comment by HellUnit** [comment]
Also checks to see if the file argument passed to it exists or not, and if not, prints an error saying as much and returns. If no file argument is passed to it, it defaults to "RustExperimental.opj". File arguments are recognized by not starting with a dash and ending with '.opj'.

**Comment by lukespragg** [comment]
Sounds good.
