### ISSUE TITLE
Patcher output to log file

### ISSUE THREAD

**Issue by lukespragg** [RustOxide/Oxide-2-Patcher#57]
This might be useful for referencing in case something went wrong.

**Comment by HellUnit** [comment]
Do you mean for the GUI? For console, you can just do 'OxidePatcher.exe -c
RustExperimental.opj > log.txt'

-- 

Antony Prince

**Comment by lukespragg** [comment]
I'm thinking it may be nice to have one by default for both.

**Comment by HellUnit** [comment]
As soon as I get VS Express to stop saying my license expired, I'll see 
what I can do.

Sent with AquaMail for Android
http://www.aqua-mail.com
